FROM node:20.8 AS build
ARG OIDC_AUTHORITY
ARG OIDC_CLIENT_ID
ARG SUMUP_APP_ID
ARG SUMUP_AFFILIATE_KEY
ENV REACT_APP_OIDC_AUTHORITY=${OIDC_AUTHORITY}
ENV REACT_APP_OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
ENV REACT_APP_SUMUP_APP_ID=${SUMUP_APP_ID}
ENV REACT_APP_SUMUP_AFFILIATE_KEY=${SUMUP_AFFILIATE_KEY}
COPY . /tmp/build
WORKDIR /tmp/build
RUN ls
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run build

FROM caddy:2.4.6-alpine
COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /tmp/build/build /srv
